#!/bin/bash

PERSON1=$1
PERSON2=$2


echo "$PERSON1:: Hi how are you $PERSON2"
echo "$PERSON2:: Iam fine what about you $PERSON1"
echo "$PERSON1:: Iam good, what are yuou studying $PERSON2"
echo "$PERSON2:: Iam studying english, what about you $PERSON1"